/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_subsurface_UsbPermissionReceiver */

#ifndef _Included_com_subsurface_UsbPermissionReceiver
#define _Included_com_subsurface_UsbPermissionReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_subsurface_UsbPermissionReceiver
 * Method:    doImport
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_subsurface_UsbPermissionReceiver_doImport
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
