/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_subsurface_Home_UsbPermissionReceiver */

#ifndef _Included_com_subsurface_Home_UsbPermissionReceiver
#define _Included_com_subsurface_Home_UsbPermissionReceiver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
